server:
  port: 8080
spring:
  session:
    store-type: none
  application:
    name: admin-managee
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/onmyoji
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
debug: true